controller_list:
  - name: fake_motor_controller
    type: $(arg fake_execution_type)
    joints:
      - Revolute 1
  - name: fake_rotor_controller
    type: $(arg fake_execution_type)
    joints:
      - Revolute 1
initial:  # Define initial robot poses per group
  - group: rotor
    pose: home