controller_list:
  - name: fake_motor_controller
    type: $(arg fake_execution_type)
    joints:
      - rev_1
  - name: fake_rotor_controller
    type: $(arg fake_execution_type)
    joints:
      - rev_1
initial:  # Define initial robot poses per group
  - group: motor
    pose: home